const salesData = [
  {
    customerName: "Ahmed Musa",
    date: "2026-01-01",
    invoiceNo: "INV-1001",
    paymentStatus: "Paid",
    totalAmount: 45000,
    totalPaid: 45000,
    sellDue: 0,
    quantity: 5,
    action: "View",
  },
  {
    customerName: "Zainab Bello",
    date: "2026-01-02",
    invoiceNo: "INV-1002",
    paymentStatus: "Partial",
    totalAmount: 78000,
    totalPaid: 50000,
    sellDue: 28000,
    quantity: 8,
    action: "View",
  },
  {
    customerName: "Sadiq Lawal",
    date: "2026-01-03",
    invoiceNo: "INV-1003",
    paymentStatus: "Unpaid",
    totalAmount: 120000,
    totalPaid: 0,
    sellDue: 120000,
    quantity: 12,
    action: "View",
  },
  {
    customerName: "Maryam Sadiya",
    date: "2026-01-04",
    invoiceNo: "INV-1004",
    paymentStatus: "Paid",
    totalAmount: 65000,
    totalPaid: 65000,
    sellDue: 0,
    quantity: 6,
    action: "View",
  },
  {
    customerName: "Ibrahim Danjuma",
    date: "2026-01-05",
    invoiceNo: "INV-1005",
    paymentStatus: "Partial",
    totalAmount: 94000,
    totalPaid: 60000,
    sellDue: 34000,
    quantity: 9,
    action: "View",
  },
  {
    customerName: "Aisha Kabir",
    date: "2026-01-06",
    invoiceNo: "INV-1006",
    paymentStatus: "Paid",
    totalAmount: 30000,
    totalPaid: 30000,
    sellDue: 0,
    quantity: 3,
    action: "View",
  },
  {
    customerName: "Abdul Rahman",
    date: "2026-01-07",
    invoiceNo: "INV-1007",
    paymentStatus: "Unpaid",
    totalAmount: 50000,
    totalPaid: 0,
    sellDue: 50000,
    quantity: 4,
    action: "View",
  },
  {
    customerName: "Fatima Sule",
    date: "2026-01-08",
    invoiceNo: "INV-1008",
    paymentStatus: "Paid",
    totalAmount: 87000,
    totalPaid: 87000,
    sellDue: 0,
    quantity: 7,
    action: "View",
  },
  {
    customerName: "Mustapha Adamu",
    date: "2026-01-09",
    invoiceNo: "INV-1009",
    paymentStatus: "Partial",
    totalAmount: 110000,
    totalPaid: 70000,
    sellDue: 40000,
    quantity: 11,
    action: "View",
  },
  {
    customerName: "Hafsat Yahaya",
    date: "2026-01-10",
    invoiceNo: "INV-1010",
    paymentStatus: "Paid",
    totalAmount: 42000,
    totalPaid: 42000,
    sellDue: 0,
    quantity: 5,
    action: "View",
  },

  // ---- Auto-generated continuation ----
  ...Array.from({ length: 200 }, (_, i) => {
    const id = 1011 + i;
    return {
      customerName: `Customer ${id}`,
      date: `2026-01-${(i + 11).toString().padStart(2, "0")}`,
      invoiceNo: `INV-${id}`,
      paymentStatus: i % 3 === 0 ? "Paid" : i % 3 === 1 ? "Partial" : "Unpaid",
      totalAmount: 50000 + i * 3000,
      totalPaid:
        i % 3 === 0 ? 50000 + i * 3000 : i % 3 === 1 ? 30000 + i * 2000 : 0,
      sellDue:
        i % 3 === 0
          ? 0
          : i % 3 === 1
            ? 50000 + i * 3000 - (30000 + i * 2000)
            : 50000 + i * 3000,
      quantity: (i % 10) + 1,
      action: "View",
    };
  }),
];

const productsData = [
  {
    _id: "ObjectId()",
    sku: "MILK-PEAK-001",
    barcode: "6224001234501",
    name: "Peak Milk 170g",
    brand: "Peak",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 950, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "PK0124A",
        expiryDate: new Date("2026-01-30"),
        quantity: 120,
        costPrice: 800,
      },
    ],

    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "ObjectId()",
    sku: "MILK-3CR-002",
    barcode: "6224001234502",
    name: "Three Crowns Milk 170g",
    brand: "Three Crowns",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 780, sellingPrice: 900, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "TC0224B",
        expiryDate: new Date("2026-02-15"),
        quantity: 100,
        costPrice: 760,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "ObjectId()",
    sku: "BEV-MILO-003",
    barcode: "6224001234503",
    name: "Milo Refill 400g",
    brand: "Milo",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "pack", purchaseUnit: "carton", conversionRate: 12 },
    pricing: { costPrice: 2100, sellingPrice: 2400, taxRate: 2.5 },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "ML0324C",
        expiryDate: new Date("2026-03-01"),
        quantity: 80,
        costPrice: 2050,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "ObjectId()",
    sku: "BEV-BVT-004",
    barcode: "6224001234504",
    name: "Bournvita 500g",
    brand: "Bournvita",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "jar", purchaseUnit: "carton", conversionRate: 12 },
    pricing: { costPrice: 2500, sellingPrice: 2850, taxRate: 2.5 },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "BV0424A",
        expiryDate: new Date("2026-04-12"),
        quantity: 60,
        costPrice: 2450,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "ObjectId()",
    sku: "RICE-MGL-005",
    barcode: "6224001234505",
    name: "Mama Gold Rice 5kg",
    brand: "Mama Gold",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "bag", purchaseUnit: "bag", conversionRate: 1 },
    pricing: { costPrice: 8500, sellingPrice: 9200, taxRate: 0 },
    stockConfig: {
      minLevel: 15,
      reorderLevel: 40,
      batchTracking: false,
      expiryTracking: false,
    },
    batches: [
      {
        batchNo: "MG0524A",
        expiryDate: new Date("2027-01-01"),
        quantity: 50,
        costPrice: 8400,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // -------- Products 6 → 40 (different brands & items) --------

  ...Array.from({ length: 35 }, (_, i) => ({
    _id: "ObjectId()",
    sku: `GEN-PROD-${String(i + 6).padStart(3, "0")}`,
    barcode: `62240012346${String(i).padStart(2, "0")}`,
    name: `Store Product ${i + 6}`,
    brand: [
      "Indomie",
      "Golden Penny",
      "Dangote",
      "Power Oil",
      "Lipton",
      "Nestle",
      "Omo",
      "Ariel",
      "CloseUp",
      "Colgate",
    ][i % 10],
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "piece", purchaseUnit: "carton", conversionRate: 12 },
    pricing: {
      costPrice: 300 + i * 25,
      sellingPrice: 400 + i * 30,
      taxRate: 2.5,
    },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: i % 2 === 0,
    },
    batches: [
      {
        batchNo: `BT${i + 100}`,
        expiryDate: new Date("2026-12-31"),
        quantity: 60 + i,
        costPrice: 280 + i * 20,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date(),
    updatedAt: new Date(),
  })),
];

const brands = [
  "Samsung",
  "Apple",
  "Sony",
  "LG",
  "Xiaomi",
  "Infinix",
  "Tecno",
  "Huawei",
  "Nokia",
  "HP",
  "Dell",
  "Lenovo",
  "Acer",
  "Asus",
  "Microsoft",
  "Canon",
  "Nikon",
  "Panasonic",
  "Bosch",
  "Philips",
  "Panasonic",
  "Oppo",
  "Vivo",
  "OnePlus",
  "Motorola",
  "TCL",
  "Hisense",
  "Razer",
  "Logitech",
  "Anker",
  "Bose",
  "JBL",
  "Midea",
  "Gree",
  "Haier",
  "RCA",
  "Sharp",
  "Hitachi",
];

const contacts = [
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
];
export default salesData;
export { productsData, contacts };
