const salesData = [
  {
    customerName: "Ahmed Musa",
    date: "2026-01-01",
    invoiceNo: "INV-1001",
    paymentStatus: "Paid",
    totalAmount: 45000,
    totalPaid: 45000,
    sellDue: 0,
    quantity: 5,
    action: "View",
  },
  {
    customerName: "Zainab Bello",
    date: "2026-01-02",
    invoiceNo: "INV-1002",
    paymentStatus: "Partial",
    totalAmount: 78000,
    totalPaid: 50000,
    sellDue: 28000,
    quantity: 8,
    action: "View",
  },
  {
    customerName: "Sadiq Lawal",
    date: "2026-01-03",
    invoiceNo: "INV-1003",
    paymentStatus: "Unpaid",
    totalAmount: 120000,
    totalPaid: 0,
    sellDue: 120000,
    quantity: 12,
    action: "View",
  },
  {
    customerName: "Maryam Sadiya",
    date: "2026-01-04",
    invoiceNo: "INV-1004",
    paymentStatus: "Paid",
    totalAmount: 65000,
    totalPaid: 65000,
    sellDue: 0,
    quantity: 6,
    action: "View",
  },
  {
    customerName: "Ibrahim Danjuma",
    date: "2026-01-05",
    invoiceNo: "INV-1005",
    paymentStatus: "Partial",
    totalAmount: 94000,
    totalPaid: 60000,
    sellDue: 34000,
    quantity: 9,
    action: "View",
  },
  {
    customerName: "Aisha Kabir",
    date: "2026-01-06",
    invoiceNo: "INV-1006",
    paymentStatus: "Paid",
    totalAmount: 30000,
    totalPaid: 30000,
    sellDue: 0,
    quantity: 3,
    action: "View",
  },
  {
    customerName: "Abdul Rahman",
    date: "2026-01-07",
    invoiceNo: "INV-1007",
    paymentStatus: "Unpaid",
    totalAmount: 50000,
    totalPaid: 0,
    sellDue: 50000,
    quantity: 4,
    action: "View",
  },
  {
    customerName: "Fatima Sule",
    date: "2026-01-08",
    invoiceNo: "INV-1008",
    paymentStatus: "Paid",
    totalAmount: 87000,
    totalPaid: 87000,
    sellDue: 0,
    quantity: 7,
    action: "View",
  },
  {
    customerName: "Mustapha Adamu",
    date: "2026-01-09",
    invoiceNo: "INV-1009",
    paymentStatus: "Partial",
    totalAmount: 110000,
    totalPaid: 70000,
    sellDue: 40000,
    quantity: 11,
    action: "View",
  },
  {
    customerName: "Hafsat Yahaya",
    date: "2026-01-10",
    invoiceNo: "INV-1010",
    paymentStatus: "Paid",
    totalAmount: 42000,
    totalPaid: 42000,
    sellDue: 0,
    quantity: 5,
    action: "View",
  },

  // ---- Auto-generated continuation ----
  ...Array.from({ length: 200 }, (_, i) => {
    const id = 1011 + i;
    return {
      customerName: `Customer ${id}`,
      date: `2026-01-${(i + 11).toString().padStart(2, "0")}`,
      invoiceNo: `INV-${id}`,
      paymentStatus: i % 3 === 0 ? "Paid" : i % 3 === 1 ? "Partial" : "Unpaid",
      totalAmount: 50000 + i * 3000,
      totalPaid:
        i % 3 === 0 ? 50000 + i * 3000 : i % 3 === 1 ? 30000 + i * 2000 : 0,
      sellDue:
        i % 3 === 0
          ? 0
          : i % 3 === 1
            ? 50000 + i * 3000 - (30000 + i * 2000)
            : 50000 + i * 3000,
      quantity: (i % 10) + 1,
      action: "View",
    };
  }),
];

const productsData = [
  {
    _id: "ObjectId()",
    sku: "MILK-PEAK-001",
    barcode: "6224001234501",
    name: "Peak Milk 170g",
    brand: "Peak",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 950, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "PK0124A",
        expiryDate: "12/02/26",
        quantity: 120,
        costPrice: 800,
      },
    ],

    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "MILK-3CR-002",
    barcode: "6224001234502",
    name: "Three Crowns Milk 170g",
    brand: "Three Crowns",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 780, sellingPrice: 900, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "TC0224B",
        expiryDate: "23/11/29",
        quantity: 100,
        costPrice: 760,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "BEV-MILO-003",
    barcode: "6224001234503",
    name: "Milo Refill 400g",
    brand: "Milo",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "pack", purchaseUnit: "carton", conversionRate: 12 },
    pricing: { costPrice: 2100, sellingPrice: 2400, taxRate: 2.5 },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "ML0324C",
        expiryDate: "28/04/27",
        quantity: 80,
        costPrice: 2050,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "BEV-BVT-004",
    barcode: "6224001234504",
    name: "Bournvita 500g",
    brand: "Bournvita",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "jar", purchaseUnit: "carton", conversionRate: 12 },
    pricing: { costPrice: 2500, sellingPrice: 2850, taxRate: 2.5 },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "BV0424A",
        expiryDate: "15/08/26",
        quantity: 60,
        costPrice: 2450,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "RICE-MGL-005",
    barcode: "6224001234505",
    name: "Mama Gold Rice 5kg",
    brand: "Mama Gold",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "bag", purchaseUnit: "bag", conversionRate: 1 },
    pricing: { costPrice: 8500, sellingPrice: 9200, taxRate: 0 },
    stockConfig: {
      minLevel: 15,
      reorderLevel: 40,
      batchTracking: false,
      expiryTracking: false,
    },
    batches: [
      {
        batchNo: "MG0524A",
        expiryDate: "3/07/26",
        quantity: 50,
        costPrice: 8400,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "MILK-PEAK-001",
    barcode: "6224001234501",
    name: "Peak Milk 170g",
    brand: "Peak",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 950, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "PK0124A",
        expiryDate: "5/08/27",
        quantity: 120,
        costPrice: 800,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-DANO-002",
    barcode: "6224001234502",
    name: "Dano Milk 170g",
    brand: "Dano",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 810, sellingPrice: 940, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "DN0224B",
        expiryDate: "18/03/26",
        quantity: 140,
        costPrice: 790,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-THREECROWNS-003",
    barcode: "6224001234503",
    name: "Three Crowns Milk 170g",
    brand: "Three Crowns",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 830, sellingPrice: 970, taxRate: 2.5 },
    stockConfig: {
      minLevel: 25,
      reorderLevel: 55,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "TC0324C",
        expiryDate: "05/04/26",
        quantity: 110,
        costPrice: 810,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-LUNA-004",
    barcode: "6224001234504",
    name: "Luna Milk 170g",
    brand: "Luna",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 780, sellingPrice: 900, taxRate: 2.5 },
    stockConfig: {
      minLevel: 15,
      reorderLevel: 40,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "LN0424D",
        expiryDate: "22/05/26",
        quantity: 160,
        costPrice: 760,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-FRISLAND-005",
    barcode: "6224001234505",
    name: "Frisland Milk 170g",
    brand: "Frisland",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 840, sellingPrice: 980, taxRate: 2.5 },
    stockConfig: {
      minLevel: 30,
      reorderLevel: 60,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "FR0524E",
        expiryDate: "10/06/26",
        quantity: 100,
        costPrice: 820,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-OLPER-006",
    barcode: "6224001234506",
    name: "Olper Milk 170g",
    brand: "Olper",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 790, sellingPrice: 920, taxRate: 2.5 },
    stockConfig: {
      minLevel: 18,
      reorderLevel: 45,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "OP0624F",
        expiryDate: "14/07/26",
        quantity: 130,
        costPrice: 770,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-NIDO-007",
    barcode: "6224001234507",
    name: "Nido Milk 170g",
    brand: "Nido",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 860, sellingPrice: 1000, taxRate: 2.5 },
    stockConfig: {
      minLevel: 22,
      reorderLevel: 52,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "ND0724G",
        expiryDate: "30/08/26",
        quantity: 90,
        costPrice: 840,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-COWBELL-008",
    barcode: "6224001234508",
    name: "Cowbell Milk 170g",
    brand: "Cowbell",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 800, sellingPrice: 930, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 48,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "CB0824H",
        expiryDate: "12/09/26",
        quantity: 150,
        costPrice: 780,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-DUTCHLADY-009",
    barcode: "6224001234509",
    name: "Dutch Lady Milk 170g",
    brand: "Dutch Lady",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 845, sellingPrice: 990, taxRate: 2.5 },
    stockConfig: {
      minLevel: 28,
      reorderLevel: 58,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "DL0924I",
        expiryDate: "01/10/26",
        quantity: 105,
        costPrice: 825,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-IDEAL-010",
    barcode: "6224001234510",
    name: "Ideal Milk 170g",
    brand: "Ideal",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 835, sellingPrice: 975, taxRate: 2.5 },
    stockConfig: {
      minLevel: 24,
      reorderLevel: 54,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "ID1024J",
        expiryDate: "15/11/26",
        quantity: 125,
        costPrice: 815,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "MILK-FAN-011",
    barcode: "6224001234511",
    name: "Fan Milk 170g",
    brand: "Fan",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 800, sellingPrice: 930, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "FN1124A",
        expiryDate: "20/12/26",
        quantity: 140,
        costPrice: 780,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-HOLLANDIA-012",
    barcode: "6224001234512",
    name: "Hollandia Milk 170g",
    brand: "Hollandia",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 845, sellingPrice: 980, taxRate: 2.5 },
    stockConfig: {
      minLevel: 22,
      reorderLevel: 52,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "HL1224B",
        expiryDate: "05/01/27",
        quantity: 110,
        costPrice: 825,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-LACTEL-013",
    barcode: "6224001234513",
    name: "Lactel Milk 170g",
    brand: "Lactel",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 860, sellingPrice: 1005, taxRate: 2.5 },
    stockConfig: {
      minLevel: 25,
      reorderLevel: 55,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "LC0125C",
        expiryDate: "17/02/27",
        quantity: 95,
        costPrice: 840,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-ARLA-014",
    barcode: "6224001234514",
    name: "Arla Milk 170g",
    brand: "Arla",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 875, sellingPrice: 1020, taxRate: 2.5 },
    stockConfig: {
      minLevel: 30,
      reorderLevel: 60,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "AR0225D",
        expiryDate: "09/03/27",
        quantity: 85,
        costPrice: 855,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-PROMASIDOR-015",
    barcode: "6224001234515",
    name: "Promasidor Milk 170g",
    brand: "Promasidor",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 790, sellingPrice: 915, taxRate: 2.5 },
    stockConfig: {
      minLevel: 18,
      reorderLevel: 48,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "PR0325E",
        expiryDate: "25/04/27",
        quantity: 150,
        costPrice: 770,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-MIKSI-016",
    barcode: "6224001234516",
    name: "Miksi Milk 170g",
    brand: "Miksi",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 770, sellingPrice: 890, taxRate: 2.5 },
    stockConfig: {
      minLevel: 15,
      reorderLevel: 40,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "MK0425F",
        expiryDate: "11/05/27",
        quantity: 170,
        costPrice: 750,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-VITA-017",
    barcode: "6224001234517",
    name: "Vita Milk 170g",
    brand: "Vita",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 950, taxRate: 2.5 },
    stockConfig: {
      minLevel: 21,
      reorderLevel: 49,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "VT0525G",
        expiryDate: "29/06/27",
        quantity: 135,
        costPrice: 800,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-DELITE-018",
    barcode: "6224001234518",
    name: "Delite Milk 170g",
    brand: "Delite",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 805, sellingPrice: 935, taxRate: 2.5 },
    stockConfig: {
      minLevel: 19,
      reorderLevel: 46,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "DL0625H",
        expiryDate: "13/07/27",
        quantity: 120,
        costPrice: 785,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-ROYAL-019",
    barcode: "6224001234519",
    name: "Royal Milk 170g",
    brand: "Royal",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 830, sellingPrice: 965, taxRate: 2.5 },
    stockConfig: {
      minLevel: 23,
      reorderLevel: 53,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "RY0725I",
        expiryDate: "21/08/27",
        quantity: 100,
        costPrice: 810,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-GOLDEN-020",
    barcode: "6224001234520",
    name: "Golden Milk 170g",
    brand: "Golden",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 850, sellingPrice: 990, taxRate: 2.5 },
    stockConfig: {
      minLevel: 26,
      reorderLevel: 56,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "GD0825J",
        expiryDate: "30/09/27",
        quantity: 115,
        costPrice: 830,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-ALPHA-021",
    barcode: "6224001234521",
    name: "Alpha Milk 170g",
    brand: "Alpha",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 810, sellingPrice: 940, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "AL0925A",
        expiryDate: "12/10/27",
        quantity: 130,
        costPrice: 790,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-BETA-022",
    barcode: "6224001234522",
    name: "Beta Milk 170g",
    brand: "Beta",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 955, taxRate: 2.5 },
    stockConfig: {
      minLevel: 18,
      reorderLevel: 48,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "BT1025B",
        expiryDate: "25/10/27",
        quantity: 150,
        costPrice: 800,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-GAMMA-023",
    barcode: "6224001234523",
    name: "Gamma Milk 170g",
    brand: "Gamma",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 835, sellingPrice: 970, taxRate: 2.5 },
    stockConfig: {
      minLevel: 22,
      reorderLevel: 52,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "GM1125C",
        expiryDate: "05/11/27",
        quantity: 120,
        costPrice: 815,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-DELTA-024",
    barcode: "6224001234524",
    name: "Delta Milk 170g",
    brand: "Delta",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 790, sellingPrice: 920, taxRate: 2.5 },
    stockConfig: {
      minLevel: 17,
      reorderLevel: 45,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "DL1225D",
        expiryDate: "19/11/27",
        quantity: 160,
        costPrice: 770,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-ECHO-025",
    barcode: "6224001234525",
    name: "Echo Milk 170g",
    brand: "Echo",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 860, sellingPrice: 1000, taxRate: 2.5 },
    stockConfig: {
      minLevel: 28,
      reorderLevel: 58,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "EC0126E",
        expiryDate: "03/12/27",
        quantity: 90,
        costPrice: 840,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-FRESH-026",
    barcode: "6224001234526",
    name: "Fresh Milk 170g",
    brand: "Fresh",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 805, sellingPrice: 935, taxRate: 2.5 },
    stockConfig: {
      minLevel: 19,
      reorderLevel: 46,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "FR0226F",
        expiryDate: "18/12/27",
        quantity: 140,
        costPrice: 785,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-GREEN-027",
    barcode: "6224001234527",
    name: "Green Milk 170g",
    brand: "Green",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 830, sellingPrice: 965, taxRate: 2.5 },
    stockConfig: {
      minLevel: 23,
      reorderLevel: 53,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "GR0326G",
        expiryDate: "02/01/28",
        quantity: 115,
        costPrice: 810,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-HAPPY-028",
    barcode: "6224001234528",
    name: "Happy Milk 170g",
    brand: "Happy",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 845, sellingPrice: 985, taxRate: 2.5 },
    stockConfig: {
      minLevel: 26,
      reorderLevel: 56,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "HP0426H",
        expiryDate: "14/01/28",
        quantity: 105,
        costPrice: 825,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-IDEA-029",
    barcode: "6224001234529",
    name: "Idea Milk 170g",
    brand: "Idea",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 800, sellingPrice: 930, taxRate: 2.5 },
    stockConfig: {
      minLevel: 21,
      reorderLevel: 49,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "ID0526I",
        expiryDate: "28/01/28",
        quantity: 150,
        costPrice: 780,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-JOY-030",
    barcode: "6224001234530",
    name: "Joy Milk 170g",
    brand: "Joy",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 870, sellingPrice: 1010, taxRate: 2.5 },
    stockConfig: {
      minLevel: 30,
      reorderLevel: 60,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "JY0626J",
        expiryDate: "10/02/28",
        quantity: 90,
        costPrice: 850,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },

  {
    _id: "ObjectId()",
    sku: "MILK-KING-031",
    barcode: "6224001234531",
    name: "King Milk 170g",
    brand: "King",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 810, sellingPrice: 945, taxRate: 2.5 },
    stockConfig: {
      minLevel: 20,
      reorderLevel: 50,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "KG0726A",
        expiryDate: "22/02/28",
        quantity: 130,
        costPrice: 790,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-LIGHT-032",
    barcode: "6224001234532",
    name: "Light Milk 170g",
    brand: "Light",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 825, sellingPrice: 960, taxRate: 2.5 },
    stockConfig: {
      minLevel: 22,
      reorderLevel: 52,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "LG0826B",
        expiryDate: "06/03/28",
        quantity: 120,
        costPrice: 805,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-MAX-033",
    barcode: "6224001234533",
    name: "Max Milk 170g",
    brand: "Max",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 840, sellingPrice: 980, taxRate: 2.5 },
    stockConfig: {
      minLevel: 24,
      reorderLevel: 54,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "MX0926C",
        expiryDate: "18/03/28",
        quantity: 100,
        costPrice: 820,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-NOVA-034",
    barcode: "6224001234534",
    name: "Nova Milk 170g",
    brand: "Nova",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 795, sellingPrice: 920, taxRate: 2.5 },
    stockConfig: {
      minLevel: 18,
      reorderLevel: 46,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "NV1026D",
        expiryDate: "02/04/28",
        quantity: 155,
        costPrice: 775,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-OMEGA-035",
    barcode: "6224001234535",
    name: "Omega Milk 170g",
    brand: "Omega",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 865, sellingPrice: 1005, taxRate: 2.5 },
    stockConfig: {
      minLevel: 28,
      reorderLevel: 58,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "OM1126E",
        expiryDate: "16/04/28",
        quantity: 90,
        costPrice: 845,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-PRIME-036",
    barcode: "6224001234536",
    name: "Prime Milk 170g",
    brand: "Prime",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 820, sellingPrice: 955, taxRate: 2.5 },
    stockConfig: {
      minLevel: 21,
      reorderLevel: 51,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "PM1226F",
        expiryDate: "29/04/28",
        quantity: 140,
        costPrice: 800,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-QUICK-037",
    barcode: "6224001234537",
    name: "Quick Milk 170g",
    brand: "Quick",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 805, sellingPrice: 940, taxRate: 2.5 },
    stockConfig: {
      minLevel: 19,
      reorderLevel: 49,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "QK0127G",
        expiryDate: "12/05/28",
        quantity: 150,
        costPrice: 785,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-RICH-038",
    barcode: "6224001234538",
    name: "Rich Milk 170g",
    brand: "Rich",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 850, sellingPrice: 990, taxRate: 2.5 },
    stockConfig: {
      minLevel: 26,
      reorderLevel: 56,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "RC0227H",
        expiryDate: "26/05/28",
        quantity: 110,
        costPrice: 830,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-SMART-039",
    barcode: "6224001234539",
    name: "Smart Milk 170g",
    brand: "Smart",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 830, sellingPrice: 970, taxRate: 2.5 },
    stockConfig: {
      minLevel: 23,
      reorderLevel: 53,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "SM0327I",
        expiryDate: "08/06/28",
        quantity: 125,
        costPrice: 810,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  {
    _id: "ObjectId()",
    sku: "MILK-TOP-040",
    barcode: "6224001234540",
    name: "Top Milk 170g",
    brand: "Top",
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "tin", purchaseUnit: "carton", conversionRate: 24 },
    pricing: { costPrice: 875, sellingPrice: 1015, taxRate: 2.5 },
    stockConfig: {
      minLevel: 30,
      reorderLevel: 60,
      batchTracking: true,
      expiryTracking: true,
    },
    batches: [
      {
        batchNo: "TP0427J",
        expiryDate: "21/06/28",
        quantity: 95,
        costPrice: 855,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  },
  // -------- Products 6 → 40 (different brands & items) --------

  ...Array.from({ length: 5 }, (_, i) => ({
    _id: "ObjectId()",
    sku: `GEN-PROD-${String(i + 6).padStart(3, "0")}`,
    barcode: `62240012346${String(i).padStart(2, "0")}`,
    name: `Store Product ${i + 6}`,
    brand: [
      "Indomie",
      "Golden Penny",
      "Dangote",
      "Power Oil",
      "Lipton",
      "Nestle",
      "Omo",
      "Ariel",
      "CloseUp",
      "Colgate",
    ][i % 10],
    categoryId: "ObjectId()",
    sellingQuantity: 1,
    units: { baseUnit: "piece", purchaseUnit: "carton", conversionRate: 12 },
    pricing: {
      costPrice: 300 + i * 25,
      sellingPrice: 400 + i * 30,
      taxRate: 2.5,
    },
    stockConfig: {
      minLevel: 10,
      reorderLevel: 30,
      batchTracking: false,
      expiryTracking: i % 2 === 0,
    },
    batches: [
      {
        batchNo: `BT${i + 100}`,
        expiryDate: new Date("2026-12-31"),
        quantity: 60 + i,
        costPrice: 280 + i * 20,
      },
    ],
    defaultSupplierId: "ObjectId()",
    status: "ACTIVE",
    createdAt: new Date().getFullYear(),
    updatedAt: new Date().getFullYear(),
  })),
];

const brands = [
  "Samsung",
  "Apple",
  "Sony",
  "LG",
  "Xiaomi",
  "Infinix",
  "Tecno",
  "Huawei",
  "Nokia",
  "HP",
  "Dell",
  "Lenovo",
  "Acer",
  "Asus",
  "Microsoft",
  "Canon",
  "Nikon",
  "Panasonic",
  "Bosch",
  "Philips",
  "Panasonic",
  "Oppo",
  "Vivo",
  "OnePlus",
  "Motorola",
  "TCL",
  "Hisense",
  "Razer",
  "Logitech",
  "Anker",
  "Bose",
  "JBL",
  "Midea",
  "Gree",
  "Haier",
  "RCA",
  "Sharp",
  "Hitachi",
];

const contacts = [
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
  {
    name: "Samira Abudullahi",
    state: "minna",
    address: "kajsdf klasdfjlkasdf",
    tel: "24234455878",
  },
];
export default salesData;
export { productsData, contacts };
